//
//
// base_defines.script
// 
// Shared Script defines
//
//

#define INVALID_JOINT					-1

#define JOINTMOD_NONE					0
#define JOINTMOD_LOCAL					1				// modifies the joint's position or orientation in joint local space
#define JOINTMOD_LOCAL_OVERRIDE			2 				// sets the joint's position or orientation in joint local space
#define JOINTMOD_WORLD					3				// modifies joint's position or orientation in model space
#define JOINTMOD_WORLD_OVERRIDE			4				// sets the joint's position or orientation in model space	

#define TURRET_YAW						0
#define TURRET_PITCH					1


